name: OS Info Workflow

on:
  push:
    branches:
      - main

jobs:
  ubuntu-jobs:
    runs-on: bilal_selfhosted_runner
    steps:
      - name: OS info
        run: |
          echo "Operating System: Ubuntu"
          echo "Hostname: $(hostname)"
          echo "Current User: $(whoami)"

  windows-jobs:
    runs-on: windows-latest
    steps:
      - name: Print OS info
        shell: cmd
        run: |
          echo Operating System: Windows
          echo Hostname: %COMPUTERNAME%
          echo Current User: %USERNAME%

  mac-jobs:
    runs-on: macos-latest
    steps:
      - name: Print OS info
        run: |
          echo "Operating System: macOS"
          echo "Hostname: $(hostname)"
          echo "Current User: $(whoami)"
